# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- build
- test
- deploy
- review
- dast
- staging
- canary
- production
- incremental rollout 10%
- incremental rollout 25%
- incremental rollout 50%
- incremental rollout 100%
- performance
- cleanup
variables:
  DEPLOY_DIR: "/var/gitlab-runner/prd/csms-server"
  PREVIOUS_COMMIT: "$CI_COMMIT_BEFORE_SHA"
before_script:
- mkdir -p $DEPLOY_DIR
build-job:
  stage: build
  script:
  - echo "Build the code..."
  - echo "Build docker complete."
unit-test-job:
  stage: test
  script:
  - echo "Running unit tests... This will take about 60 seconds."
  - sleep 5
  - echo "Code coverage is 90%"
lint-test-job:
  stage: test
  script:
  - echo "Linting code... This will take about 10 seconds."
  - sleep 5
  - echo "No lint issues found."
deploy-job:
  stage: deploy
  image: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
    DOCKER_USERNAME: "$CI_DOCKER_USER"
    DOCKER_PASSWORD: "$CI_DOCKER_PASSWORD"
    DOCKER_IMAGE_NAME: kabina/csms-server
    DOCKER_IMAGE_TAG: latest
  services:
  - name: docker:dind
    alias: docker
    command:
    - "--tls=false"
  script:
  - echo $CI_DOCKER_USER
  - echo $CI_DOCKER_PASSWORD
  - echo "Docker deploy Start ..."
  - docker login -u $CI_DOCKER_USER -p $CI_DOCKER_PASSWORD
  - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG -f Dockerfile_gunicorn .
  - docker tag $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
  - docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
  - docker images
  - sleep 10
  - echo $DOCKER_IMAGE_NAME $DOCKER_IMAGE_TAG
  - docker run -d -p 5000:5000 $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
  - docker ps
  - sleep 10
  - docker ps -a
  - docker images
  - echo "Docker deploy complete ..."
  after_script:
  - docker login -u $CI_DOCKER_USER -p $CI_DOCKER_PASSWORD
  - docker pull kabina/csms-server:latest
  - docker run -d kabina/csms-server:latest
  rules:
  - changes:
    - src/**/*
    when: always
sast:
  stage: test
include:
- template: Auto-DevOps.gitlab-ci.yml
