# Use an official Python runtime as a parent image
FROM python:3.10

#RUN useradd -ms /bin/bash 'appuser'
#USER appuser


# Copy the rest of the application code
COPY ./src /app

# Set the working directory to /app
WORKDIR /app


# Create and activate a virtual environment
#RUN python -m venv /app/venv
ENV PATH="/app:$PATH"
RUN pip install --upgrade pip

# Install gunicorn
RUN pip install confluent_kafka
RUN pip install ocpp
RUN pip install psycopg2
RUN pip install websockets
RUN pip install aiokafka

# Make port 5000 available to the world outside this container
# Define environment variable

EXPOSE 8765

#RUN chmod +x /app/runapp.sh
#CMD ["runapp.sh"]
# Run app.py when the container launches
CMD ["runsock.sh"]
