# Use an official Python runtime as a parent image
FROM python:3.10

#RUN useradd -ms /bin/bash 'appuser'
#USER appuser

# Set the working directory to /app
WORKDIR /app

# Copy the rest of the application code
COPY ./src /app


# Create and activate a virtual environment
#RUN python -m venv /app/venv
#ENV PATH="/app/venv/bin:$PATH"
RUN pip install --upgrade pip

# Install gunicorn
RUN pip install confluent_kafka
RUN pip install ocpp
RUN pip install psycopg2
RUN pip install websockets

# Make port 5000 available to the world outside this container
# Define environment variable
ENV NAME World

EXPOSE 8765

#RUN chmod +x /app/runapp.sh
#CMD ["runapp.sh"]
# Run app.py when the container launches
CMD ["python", "/app/csms_server.py"]
